general.live_config_reload = true
colors.draw_bold_text_with_bright_colors = true
general.working_directory = "D:\\"

[colors.primary]
background = "#1e2127"
foreground = "#D8DEE9"

[font]
size = 14

  [font.normal]
  family = "FiraCode Nerd Font"
  style = "Regular"

  [font.bold]
  family = "FiraCode Nerd Font"
  style = "Bold"

  [font.italic]
  family = "FiraCode Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "FiraCode Nerd Font"
  style = "Bold Italic"

[window]
startup_mode = "Windowed"
dynamic_padding = true
decorations = "none"
opacity = 0.95

  [window.padding]
  x = 10
  y = 32

  [window.dimensions]
  columns = 135
  lines = 37

  [window.position]
  x = 5
  y = 5

[terminal.shell]
program = "nu.exe"

[scrolling]
history = 1_000

[cursor.style]
shape = "Beam"
blinking = "on"

[cursor.vi_mode_style]
shape = "block"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"
