-- return {
--   ["nvim-treesitter/nvim-treesitter"] = {
--     ensure_installed = {
--       "bash",
--       "comment",
--       "cpp",
--       "css",
--       "graphql",
--       "html",
--       "javascript",
--       "json",
--       "lua",
--       "regex",
--       "tsx",
--       "typescript",
--       "vim",
--       "yaml",
--       "python",
--     },
--   },
--
--   ["williamboman/mason.nvim"] = {
--     ensure_installed = {
--       -- lua stuff
--       "lua-language-server",
--       "stylua",
--
--       -- web dev
--       "css-lsp",
--       "deno",
--       "emmet-ls",
--       "eslint-lsp",
--       "html-lsp",
--       "json-lsp",
--       "typescript-language-server",
--       "yaml-language-server",
--
--       -- shell
--       "shellcheck",
--
--       -- python
--       "pyright"
--     },
--   },
-- }
